disable:
  target:
    entity:
      integration: pi_hole_v6
      domain: switch
  fields:
    duration:
      required: true
      example: "00:00:15"
      selector:
        text:
enable:
  target:
    entity:
      integration: pi_hole_v6
      domain: switch

